### ISSUE TITLE
A WARNING from ax.storage.sqa_store.save when saving an Experiment with MapData

### ISSUE THREAD

**Issue by alxfed** [facebook/Ax#1026] opened 2022-07-18 19:18 UTC
I'm trying to save an experiment with a freshly 'attached' MapData object created by **.fetch_trial_data_multi**.
The new data is supposed to replace the existing data, stored in the data_v2 table, because **overwrite_existing_data** is set to True on all the metrics involved.
I'm getting the following warning:

`[WARNING 07-18 13:34:38] ax.storage.sqa_store.save: Error encountered when copying db_ids from Experiment(ExperimentName) back to user-facing object Experiment(ExperimentName). This might cause issues if you re-save this experiment. Exception: Error encountered while traversing source ['_data_by_trial', 0, 1658169130577, '_map_key_infos', '[<ax.core.map_data.MapKeyInfo object at 0x7faf05656be0>, <ax.core.map_data.MapKeyInfo object at 0x7faf05656d30>]'] and target ['_data_by_trial', 0, 1658169130577, '_map_key_infos', '[<ax.core.map_data.MapKeyInfo object at 0x7faf062a5fd0>, <ax.core.map_data.MapKeyInfo object at 0x7faf059580d0>]']: TypeError encountered during sorting: '<' not supported between instances of 'method' and 'method'`

Do I understand it right that the phrase "TypeError encountered during sorting: '<' not supported between instances of 'method' and 'method'" signifies that your software tried to compare incomparable and this is a bug? 
Or is this because I should have used the same **map_key_infos** list on every MapData that I'm attaching to the experiment? ... on every MapData object from every MapMetric combined into a resulting MapData object for the trial?
Please explain.

**Comment by bernardbeckerman** [comment] 2022-07-20 15:36
Hi @alxfed, thanks for reporting this! I just saw you closed this out - is this because your hypothesis from before

> is this because I should have used the same map_key_infos list on every MapData that I'm attaching to the experiment?

was correct? Just wanted to follow up and get closure for posterity.

**Comment by alxfed** [comment] 2022-07-20 18:12
I looked into what you did to the registries and decided to redo these MapMetrics/MapData/fidelities you your 0.2.5.1 version (I kept working on 0.2.3 until now). There I will trace these problems with missing db_id in detail. I saw and reported one of those before, but as we can see, the remnants are still there somewhere. 
Then I will be able to post a more detailed bug report. 
...otherwise it would be too much work for you.

**Comment by alxfed** [comment] 2022-07-21 21:52
The warning/error comes from the function `_copy_db_ids_if_possible`(new_obj: Any, obj: Any), starting from line 492 of storage/sqa_store/**save.py**
As I understand from the comment, and I quote: "# Raise these warnings in unittests only" 'the original intent' as they say it in the Supreme Court was to have the code on lines 498-505 like this:
<pre>
# Raise these warnings in unittests only
if os.environ.get("TESTENV"):
    raise e
    logger.warning(
        f"Error encountered when copying db_ids from {new_obj} "
        f"back to user-facing object {obj}. "
        "This might cause issues if you re-save this experiment. "
        f"Exception: {e}"
    )
</pre>
But right now it is:
<pre>
# Raise these warnings in unittests only
if os.environ.get("TESTENV"):
    raise e
logger.warning(
    f"Error encountered when copying db_ids from {new_obj} "
    f"back to user-facing object {obj}. "
    "This might cause issues if you re-save this experiment. "
    f"Exception: {e}"
)`
</pre>

I think there is no need to spend a whole pull request on this... Just correct this mistype.

As to the particular use-case with MapData there is no need in assigning db_id to MapKeyInfo objects, they are not stored anywhere in the db independently... it would be interesting to know what was the idea of using objects here in the first place...? Maybe the thinking was that at some point a fidelity inheriting from this class will have some 'descriptors' as they call them, updating automatically according to the current stat of the surrogate model...? Dunno.

**Comment by lena-kashtelyan** [comment] 2022-08-08 19:11
@alxfed, I think the current form of that code snippet is actually intentional; it is the comment that is incorrect : ) It should say "# Raise these errors in unittests only, otherwise just log a warning". 

Generally these issues in `_copy_db_ids` are significant, and we do want to raise warnings when we encounter them. On new version of Ax and with updated registries, you are seeing this same warning you reported in the issue originally? It's a bug in that case, and we'll need to look into it.

**Comment by alxfed** [comment] 2022-08-08 23:27
Yes. On _any_ version (0.2.5.1 included) when I'm trying to save MapData in the SQA store the WARNING is raised.

**Comment by lena-kashtelyan** [comment] 2022-08-10 19:37
We'll look into it, thank you for reporting!

**Comment by mpolson64** [comment] 2022-08-10 21:40
Alex, we're having some trouble reproducing this error on our end. Could we ask you for a minimal reproduction of this error and a full stack trace?

**Comment by lena-kashtelyan** [comment] 2022-09-13 16:04
Closing this issue as inactive. @alxfed, please reopen this if you do follow up with a repro!

**Closed by lena-kashtelyan** 2022-09-13 16:04 UTC
Labels: bug, requires repro or more info
