### ISSUE TITLE
JSON save broken for botorch_methods

### ISSUE THREAD

**Issue by perspectivisme** [facebook/Ax#302] opened 2020-04-23 11:46 UTC
Dear Ax project,

First of all, thank you for this very useful tool that is AX.

You have introduced new botorch generation strategies, such as Knowledge Gradients, on the 26th of Feb, available in ax.benchmark.botorch_methods

They execute perfectly, but unfortunately it is no longer possible to save the checkpoints using JSON.

How to reproduce:
* Take your Hartmann tutorial for services, 
* add an import : from ax.benchmark.botorch_methods import singletask_KG
* add a parameter to the AxClient contructor : ax_client = AxClient(generation_strategy=singletask_KG).
* let the tutorial run, until you have some best_parameters
* try to save using : ax_client.save_to_json_file(‘bug_tmp.json’)

Saving throws an exception (JSONEncodeError). All the new standard generation strategies are affected (singletask_NEI, singletask_KG, singletask_MES, fixednoise_NEI, etc)

**Comment by stevemandala** [comment] 2020-04-23 17:01
Hey @perspectivisme, I was able to reproduce the error thanks to your instructions. It appears we didn't add support for JSON encoding when we released these new generation strategies. I'll investigate to see what it would take to get this added.

**Comment by stevemandala** [comment] 2020-04-23 19:14
Update: Found the missing piece, it looks like the callable serialization hasn't been extended for the generation strategy kwargs, should be a relatively simple fix, should be able to get it out this week.

**Comment by perspectivisme** [comment] 2020-04-23 19:40
That's good news, thank you in advance!

**Comment by EricZLou** [comment] 2020-07-01 16:20
Hey @perspectivisme -- just an update that the fix is on the master branch and will be included with the next stable release of Ax. Let us know if you run into anything else!

**Comment by lena-kashtelyan** [comment] 2020-07-17 18:04
@perspectivisme, this is now fixed on the latest stable version, 0.1.14.

**Closed by lena-kashtelyan** 2020-07-17 18:04 UTC
Labels: fixready
