### ISSUE TITLE
[Bug]: Using botorch_acqf_class=qKnowledgeGradient with botorch modular

### ISSUE THREAD

**Issue by ThomasDodd97** [facebook/Ax#2984] opened 2024-10-29 16:21 UTC
### What happened?

I attempted to run an optimisation using the qKnowledgeGradient acquisition function (botorch_acqf_class) within a botorch_modular context, and obtained an error concerning the optimizer - the error was as follows: "TypeError: ax.models.torch.botorch_modular.optimizer_argparse._argparse_base() got multiple values for keyword argument 'optimizer'"

My solution was to go to the offending file (models/torch/botorch_modular/optimizer_argparse.py), and then onward to the offending function "def _argparse_kg", thereunder to lines 145 to 151; here I commented out the line specifying the optimizer, since I could see this was already being specified in the **kwargs dictionary.

    base_options = _argparse_base(
        acqf,
        num_restarts=num_restarts,
        raw_samples=raw_samples,
        optimizer_options=optimizer_options,
        optimizer="optimize_acqf",
        **kwargs,
    )

to

    base_options = _argparse_base(
        acqf,
        num_restarts=num_restarts,
        raw_samples=raw_samples,
        optimizer_options=optimizer_options,
        # optimizer="optimize_acqf",
        **kwargs,
    )

Just wondering whether this was incredibly naive and likely to cause mayhem elsewhere in the code, or whether a fix worth implementing?

### Please provide a minimal, reproducible example of the unexpected behavior.

```python
import numpy as np
from ax.service.ax_client import AxClient
from ax.modelbridge.generation_strategy import GenerationStrategy, GenerationStep
from ax.modelbridge.registry import Models
from ax.models.torch.botorch_modular.surrogate import Surrogate
from botorch.models.gp_regression import SingleTaskGP
from botorch.acquisition.knowledge_gradient import qKnowledgeGradient
from ax.service.utils.instantiation import ObjectiveProperties

gs = GenerationStrategy(
                steps=[
                    GenerationStep(
                        # model=Models.GPEI,
                        model=Models.BOTORCH_MODULAR,
                        num_trials=-1,  # No limitation on how many trials should be produced from this step
                        model_kwargs={  # Kwargs to pass to `BoTorchModel.__init__`
                            "surrogate": Surrogate(SingleTaskGP),
                            "botorch_acqf_class": qKnowledgeGradient,
                        },
                    ),
                ]
            )
AxClient_obj = AxClient(generation_strategy=gs)
AxClient_obj.create_experiment(
    name="Example",
    parameters=[
    {"name":"x1", "type":"range","bounds":list([-10.0,10.0]),"value_type":"float"},
    {"name":"x2", "type":"range","bounds":list([-10.0,10.0]),"value_type":"float"}
],
    objectives= {"t1":ObjectiveProperties(minimize=True)}
)

def booth(x,y):
    tmp1 = (x+(2*y)-7)**2
    tmp2 = ((2*x)+y-5)**2
    return tmp1+tmp2

GridSampledPriorIndexes = [int(0),int(1),int(2),int(3),int(4),int(5),int(6),int(7),int(8)]
GridSamplePriorx1 = [-10.0,0.0,10.0,-10.0,0.0,10.0,-10.0,0.0,10.0]
GridSamplePriorx2 = [-10.0,-10.0,-10.0,0.0,0.0,0.0,10.0,10.0,10.0]
GridSampledPriorEvaluationst1 = []
for x1,x2 in zip(GridSamplePriorx1,GridSamplePriorx2):
    GridSampledPriorEvaluationst1.append(booth(x1,x2))

for Idx,x1,x2 in zip(GridSampledPriorIndexes,GridSamplePriorx1,GridSamplePriorx2):
    AxClient_obj.attach_trial(parameters={"x1":x1,"x2":x2})

for RunningTrialsIdx_flt,Evaluation_flt in zip(GridSampledPriorIndexes,GridSampledPriorEvaluationst1):
    AxClient_obj.complete_trial(trial_index=int(RunningTrialsIdx_flt),raw_data={"t1":(Evaluation_flt)})

AxClient_obj.get_next_trials(max_trials=1)
```

### Please paste any relevant traceback/logs produced by the example provided.

```shell
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[2], line 4
      2 AxClient_obj = ExperimentalMethods_obj.ExperimentInitialiser_func(OptimisationSetup_obj)
      3 for round in range(OptimisationSetup_obj.NoOfBayesianIterations_int):
----> 4     ExperimentalMethods_obj.TrialsStartor_func(AxClient_obj,OptimisationSetup_obj)
      5     ExperimentalMethods_obj.TrialsCompletor_func(AxClient_obj,OptimisationSetup_obj)
      6     df = AxClient_obj.get_trials_data_frame()

File ~/Library/CloudStorage/OneDrive-MillfieldEnterprisesLimited/Cambridge/GitHub/BO4ACST/BO4ACST_Modules/ExperimentalMethods.py:173, in ExperimentalMethods_class.TrialsStartor_func(self, AxClient_obj, OptimisationSetup_obj)
    171 else:
    172     print("There are no trials currently running - initialising Bayesian iteration trials.")
--> 173     AxClient_obj.get_next_trials(max_trials=OptimisationSetup_obj.NoOfBayesianTrialsPerIteration_int)
    174     AxClient_obj.save_to_json_file(OptimisationSetup_obj.ExperimentFilePath_str)

File ~/miniconda3/envs/BO4ACST_env/lib/python3.11/site-packages/ax/service/ax_client.py:638, in AxClient.get_next_trials(self, max_trials, ttl_seconds, fixed_features)
    636 for _ in range(max_trials):
    637     try:
--> 638         params, trial_index = self.get_next_trial(
    639             ttl_seconds=ttl_seconds, fixed_features=fixed_features
    640         )
    641         trials_dict[trial_index] = params
    642     except OptimizationComplete as err:

File ~/miniconda3/envs/BO4ACST_env/lib/python3.11/site-packages/ax/utils/common/executils.py:167, in retry_on_exception.<locals>.func_wrapper.<locals>.actual_wrapper(*args, **kwargs)
    163             wait_interval = min(
    164                 MAX_WAIT_SECONDS, initial_wait_seconds * 2 ** (i - 1)
    165             )
    166             time.sleep(wait_interval)
--> 167         return func(*args, **kwargs)
    169 # If we are here, it means the retries were finished but
    170 # The error was suppressed. Hence return the default value provided.
    171 return default_return_on_suppression

File ~/miniconda3/envs/BO4ACST_env/lib/python3.11/site-packages/ax/service/ax_client.py:543, in AxClient.get_next_trial(self, ttl_seconds, force, fixed_features)
    539         raise OptimizationShouldStop(message=global_stopping_message)
    541 try:
    542     trial = self.experiment.new_trial(
--> 543         generator_run=self._gen_new_generator_run(
    544             fixed_features=fixed_features
    545         ),
    546         ttl_seconds=ttl_seconds,
    547     )
    548 except MaxParallelismReachedException as e:
    549     if self._early_stopping_strategy is not None:

File ~/miniconda3/envs/BO4ACST_env/lib/python3.11/site-packages/ax/service/ax_client.py:1781, in AxClient._gen_new_generator_run(self, n, fixed_features)
   1773 fixed_feats = (
   1774     InstantiationBase.make_fixed_observation_features(
   1775         fixed_features=fixed_features
   (...)
   1778     else None
   1779 )
   1780 with with_rng_seed(seed=self._random_seed):
-> 1781     return not_none(self.generation_strategy).gen(
   1782         experiment=self.experiment,
   1783         n=n,
   1784         pending_observations=self._get_pending_observation_features(
   1785             experiment=self.experiment
   1786         ),
   1787         fixed_features=fixed_feats,
   1788     )

File ~/miniconda3/envs/BO4ACST_env/lib/python3.11/site-packages/ax/modelbridge/generation_strategy.py:372, in GenerationStrategy.gen(self, experiment, data, n, pending_observations, **kwargs)
    337 def gen(
    338     self,
    339     experiment: Experiment,
   (...)
    343     **kwargs: Any,
    344 ) -> GeneratorRun:
    345     """Produce the next points in the experiment. Additional kwargs passed to
    346     this method are propagated directly to the underlying model's `gen`, along
    347     with the `model_gen_kwargs` set on the current generation node.
   (...)
    370             resuggesting points that are currently being evaluated.
    371     """
--> 372     return self._gen_multiple(
    373         experiment=experiment,
    374         num_generator_runs=1,
    375         data=data,
    376         n=n,
    377         pending_observations=pending_observations,
    378         **kwargs,
    379     )[0]

File ~/miniconda3/envs/BO4ACST_env/lib/python3.11/site-packages/ax/modelbridge/generation_strategy.py:786, in GenerationStrategy._gen_multiple(self, experiment, num_generator_runs, data, n, pending_observations, **model_gen_kwargs)
    784 for _ in range(num_generator_runs):
    785     try:
--> 786         generator_run = self._curr.gen(
    787             n=n,
    788             pending_observations=pending_observations,
    789             arms_by_signature_for_deduplication=(
    790                 experiment.arms_by_signature_for_deduplication
    791             ),
    792             **model_gen_kwargs,
    793         )
    795     except DataRequiredError as err:
    796         # Model needs more data, so we log the error and return
    797         # as many generator runs as we were able to produce, unless
    798         # no trials were produced at all (in which case its safe to raise).
    799         if len(generator_runs) == 0:

File ~/miniconda3/envs/BO4ACST_env/lib/python3.11/site-packages/ax/modelbridge/generation_node.py:807, in GenerationStep.gen(self, n, pending_observations, max_gen_draws_for_deduplication, arms_by_signature_for_deduplication, **model_gen_kwargs)
    799 def gen(
    800     self,
    801     n: Optional[int] = None,
   (...)
    805     **model_gen_kwargs: Any,
    806 ) -> GeneratorRun:
--> 807     gr = super().gen(
    808         n=n,
    809         pending_observations=pending_observations,
    810         max_gen_draws_for_deduplication=max_gen_draws_for_deduplication,
    811         arms_by_signature_for_deduplication=arms_by_signature_for_deduplication,
    812         **model_gen_kwargs,
    813     )
    814     gr._generation_step_index = self.index
    815     return gr

File ~/miniconda3/envs/BO4ACST_env/lib/python3.11/site-packages/ax/modelbridge/generation_node.py:334, in GenerationNode.gen(self, n, pending_observations, max_gen_draws_for_deduplication, arms_by_signature_for_deduplication, **model_gen_kwargs)
    331 # Keep generating until each of `generator_run.arms` is not a duplicate
    332 # of a previous arm, if `should_deduplicate is True`
    333 while should_generate_run:
--> 334     generator_run = self._gen(
    335         n=n,
    336         pending_observations=pending_observations,
    337         **model_gen_kwargs,
    338     )
    339     should_generate_run = (
    340         self.should_deduplicate
    341         and arms_by_signature_for_deduplication
   (...)
    345         )
    346     )
    347     n_gen_draws += 1

File ~/miniconda3/envs/BO4ACST_env/lib/python3.11/site-packages/ax/modelbridge/generation_node.py:396, in GenerationNode._gen(self, n, pending_observations, **model_gen_kwargs)
    392 if n is None and model_spec.model_gen_kwargs:
    393     # If `n` is not specified, ensure that the `None` value does not
    394     # override the one set in `model_spec.model_gen_kwargs`.
    395     n = model_spec.model_gen_kwargs.get("n", None)
--> 396 return model_spec.gen(
    397     n=n,
    398     # For `pending_observations`, prefer the input to this function, as
    399     # `pending_observations` are dynamic throughout the experiment and thus
    400     # unlikely to be specified in `model_spec.model_gen_kwargs`.
    401     pending_observations=pending_observations,
    402     **model_gen_kwargs,
    403 )

File ~/miniconda3/envs/BO4ACST_env/lib/python3.11/site-packages/ax/modelbridge/model_spec.py:235, in ModelSpec.gen(self, **model_gen_kwargs)
    230 fitted_model = self.fitted_model
    231 model_gen_kwargs = consolidate_kwargs(
    232     kwargs_iterable=[self.model_gen_kwargs, model_gen_kwargs],
    233     keywords=get_function_argument_names(fitted_model.gen),
    234 )
--> 235 generator_run = fitted_model.gen(**model_gen_kwargs)
    236 fit_and_std_quality_and_generalization_dict = (
    237     get_fit_and_std_quality_and_generalization_dict(
    238         fitted_model_bridge=self.fitted_model,
    239     )
    240 )
    241 generator_run._gen_metadata = (
    242     {} if generator_run.gen_metadata is None else generator_run.gen_metadata
    243 )

File ~/miniconda3/envs/BO4ACST_env/lib/python3.11/site-packages/ax/modelbridge/base.py:777, in ModelBridge.gen(self, n, search_space, optimization_config, pending_observations, fixed_features, model_gen_options)
    770 base_gen_args = self._get_transformed_gen_args(
    771     search_space=search_space,
    772     optimization_config=optimization_config,
    773     pending_observations=pending_observations,
    774     fixed_features=fixed_features,
    775 )
    776 # Apply terminal transform and gen
--> 777 gen_results = self._gen(
    778     n=n,
    779     search_space=base_gen_args.search_space,
    780     optimization_config=base_gen_args.optimization_config,
    781     pending_observations=base_gen_args.pending_observations,
    782     fixed_features=base_gen_args.fixed_features,
    783     model_gen_options=model_gen_options,
    784 )
    786 observation_features = gen_results.observation_features
    787 best_obsf = gen_results.best_observation_features

File ~/miniconda3/envs/BO4ACST_env/lib/python3.11/site-packages/ax/modelbridge/torch.py:690, in TorchModelBridge._gen(self, n, search_space, pending_observations, fixed_features, model_gen_options, optimization_config)
    681 search_space_digest, torch_opt_config = self._get_transformed_model_gen_args(
    682     search_space=search_space,
    683     pending_observations=pending_observations,
   (...)
    686     optimization_config=optimization_config,
    687 )
    689 # Generate the candidates
--> 690 gen_results = not_none(self.model).gen(
    691     n=n,
    692     search_space_digest=search_space_digest,
    693     torch_opt_config=torch_opt_config,
    694 )
    696 gen_metadata = gen_results.gen_metadata
    697 if (
    698     isinstance(optimization_config, MultiObjectiveOptimizationConfig)
    699     and gen_metadata.get("objective_thresholds", None) is not None
   (...)
    703     # if using a hypervolume based acquisition function, then
    704     # the inferred objective thresholds are in gen_metadata.

File ~/miniconda3/envs/BO4ACST_env/lib/python3.11/site-packages/ax/models/torch/botorch_modular/model.py:423, in BoTorchModel.gen(self, n, search_space_digest, torch_opt_config)
    417 acqf = self._instantiate_acquisition(
    418     search_space_digest=search_space_digest,
    419     torch_opt_config=torch_opt_config,
    420     acq_options=acq_options,
    421 )
    422 botorch_rounding_func = get_rounding_func(torch_opt_config.rounding_func)
--> 423 candidates, expected_acquisition_value, weights = acqf.optimize(
    424     n=n,
    425     search_space_digest=search_space_digest,
    426     inequality_constraints=_to_inequality_constraints(
    427         linear_constraints=torch_opt_config.linear_constraints
    428     ),
    429     fixed_features=torch_opt_config.fixed_features,
    430     rounding_func=botorch_rounding_func,
    431     optimizer_options=checked_cast(dict, opt_options),
    432 )
    433 gen_metadata = self._get_gen_metadata_from_acqf(
    434     acqf=acqf,
    435     torch_opt_config=torch_opt_config,
    436     expected_acquisition_value=expected_acquisition_value,
    437 )
    438 return TorchGenResults(
    439     points=candidates.detach().cpu(),
    440     weights=weights,
    441     gen_metadata=gen_metadata,
    442 )

File ~/miniconda3/envs/BO4ACST_env/lib/python3.11/site-packages/ax/models/torch/botorch_modular/acquisition.py:460, in Acquisition.optimize(self, n, search_space_digest, inequality_constraints, fixed_features, rounding_func, optimizer_options)
    457         optimizer = "optimize_acqf_mixed"
    459 # Prepare arguments for optimizer
--> 460 optimizer_options_with_defaults = optimizer_argparse(
    461     self.acqf,
    462     bounds=bounds,
    463     q=n,
    464     optimizer_options=optimizer_options,
    465     optimizer=optimizer,
    466 )
    467 post_processing_func = get_post_processing_func(
    468     rounding_func=rounding_func,
    469     optimizer_options=optimizer_options_with_defaults,
    470 )
    471 if fixed_features is not None:

File ~/miniconda3/envs/BO4ACST_env/lib/python3.11/site-packages/botorch/utils/dispatcher.py:93, in Dispatcher.__call__(self, *args, **kwargs)
     91 func = self.__getitem__(types=types)
     92 try:
---> 93     return func(*args, **kwargs)
     94 except MDNotImplementedError:
     95     # Traverses registered methods in order, yields whenever a match is found
     96     funcs = self.dispatch_iter(*types)

File ~/miniconda3/envs/BO4ACST_env/lib/python3.11/site-packages/ax/models/torch/botorch_modular/optimizer_argparse.py:146, in _argparse_kg(acqf, q, bounds, num_restarts, raw_samples, frac_random, optimizer_options, **kwargs)
    138 """
    139 Argument constructor for optimization with qKG, differing from the
    140 base case in that it computes and returns initial conditions.
   (...)
    143 allows for specifying `frac_random`.
    144 """
    145 from copy import deepcopy
--> 146 base_options = _argparse_base(
    147     acqf,
    148     num_restarts=num_restarts,
    149     raw_samples=raw_samples,
    150     optimizer_options=optimizer_options,
    151     optimizer="optimize_acqf",
    152     **kwargs,
    153 )
    155 initial_conditions = gen_one_shot_kg_initial_conditions(
    156     acq_function=acqf,
    157     bounds=bounds,
   (...)
    165     },
    166 )
    168 return {
    169     **base_options,
    170     Keys.BATCH_INIT_CONDITIONS: initial_conditions,
    171 }

TypeError: ax.models.torch.botorch_modular.optimizer_argparse._argparse_base() got multiple values for keyword argument 'optimizer'
```

### Ax Version

0.4.3

### Python Version

3.11.10

### Operating System

macOS Sonoma Version 14.6.1

### Code of Conduct

- [X] I agree to follow Ax's Code of Conduct

**Comment by esantorella** [comment] 2024-10-30 14:20
Hi, thanks for reporting this and for the reproducible example. This definitely looks like a bug. I'll look into what fix is appropriate. I'm not sure whether we want to require the optimizer to be `optimize_acqf` and ensure no other optimizer is passed, or if we should be allowing a user-specified optimizer to override the default of `optimize_acqf`. Either way, you definitely shouldn't be getting that exception.

**Comment by esantorella** [comment] 2024-10-31 18:02
Should be fixed, but feel free to reopen if you run into the same issue again, or open a new issue for any new problems.

**Closed by esantorella** 2024-10-31 18:02 UTC
Labels: bug

**Comment by ThomasDodd97** [comment] 2024-11-01 09:56
Superb, effort much appreciated Elizabeth!
All the best,
Thomas
