### ISSUE TITLE
[QUESTION] Add prior knowledge to the underlying GP model

### ISSUE THREAD

**Issue by farrokhsiar** [facebook/Ax#828] opened 2022-03-02 18:00 UTC
A general question: what's the best way to include prior knowledge into the underlying GP model? like if I have some prior from previous experiments, how should I include it in the underlying model and sampling strategy?

**Comment by eytan** [comment] 2022-03-02 18:22
cc @bletham , @sdaulton

**Comment by bernardbeckerman** [comment] 2022-03-04 16:25
@farrokhsiar to clarify, are you looking to incorporate information/trials from a previous Ax experiment, or are you looking to provide some prior that comes from, e.g., previous knowledge? The former is more straightforward and can be achieved by attaching trials from the previous expeirment using [`Experiment.warm_start_from_old_experiment`](https://ax.dev/api/_modules/ax/core/experiment.html#Experiment.warm_start_from_old_experiment). If you're looking to do the latter, please let me know and I can follow upon exactly how you might go about doing that.

**Comment by qingfeng10** [comment] 2022-03-04 17:39
+1 to what @bernardbeckerman said. If you have historical data, you can incorporate them into the experiment. One thing to note. It would be good to check the relevance of the data in case of negative transfer. 

@farrokhsiar, re the B) scenario you brought up above. My understanding is that you like to use different GP models. If so, you can specify your own [model_constructor](https://github.com/facebook/Ax/blob/main/ax/models/torch/botorch.py#L113) rather than using the default `[get_and_fit_model](https://github.com/facebook/Ax/blob/main/ax/models/torch/botorch_defaults.py#L49)`  In particular, you can modify `[_get_model]`(https://github.com/facebook/Ax/blob/main/ax/models/torch/botorch_defaults.py#L517) to use GP with the selected kernel. 

Let me know whether this makes sense. It might be a bit deep in the code. So cc @lena-kashtelyan to see whether Modular Botorch can give a simpler solution.

**Comment by farrokhsiar** [comment] 2022-03-04 17:53
Thanks. Lat's say I have additional information about my response, which is a known normal distribution with `mean' and `sem`.  Any way to specify that, or I should still use the model constructor?

**Comment by Balandat** [comment] 2022-03-07 00:29
> Lat's say I have additional information about my response, which is a known normal distribution with mean' and sem`.

What exactly do you mean by "response" here?
- Are you talking about putting this Normal as a prior over the search space (domain) to indicate prior knowledge where the maximizer may be?
- Or is this auxiliary information about the observations `Y` (e.g. marginalized over the whole domain)?
- Or are you talking about this being the noise distribution on an individual observation level (e.g. the true observed value at some point is `mean'`, but you know that the observation is a draw from `N(mean', sem')`?

**Comment by farrokhsiar** [comment] 2022-03-07 04:00
I should say the first case, the addition of the prior over the search space.

**Comment by Balandat** [comment] 2022-03-07 14:09
Is this information about the location of the optimizer, or can you say something about the function value as well? In the latter case, could this just be an included as the prior mean function of the GP?

**Comment by farrokhsiar** [comment] 2022-03-07 19:14
Thanks for the clarification. I should have been more explicit in my question which is about the latter part: what's the easiest way to modify the prior mean function of the GP when using AX service API?

**Comment by Balandat** [comment] 2022-03-07 22:18
So the basic way is to define a custom `GenerationStrategy` with a`GenerationStep` that uses the custom model. We have a new "modular botorch model" abstraction that should make that relatively straightforward, but unfortunately it looks like we currently do not yet support customizing the mean function (cc @lena-kashtelyan)

How to do this in the legacy API is described in this tutorial: https://botorch.org/tutorials/custom_botorch_model_in_ax

I believe @saitcakmak is currently working on updating that tutorial to also show how to use this in conjunction with the Service API, so a draft of that would be a good start.

**Comment by farrokhsiar** [comment] 2022-03-08 03:57
Thanks, Max. I appreciate it if I can get access to the draft.

**Comment by farrokhsiar** [comment] 2022-03-08 17:21
Thanks a lot. This is very helpful.

**Comment by saitcakmak** [comment] 2022-03-11 21:57
Hi @farrokhsiar. We identified the cause of the above mentioned issue and fixed it in Ax v0.2.4 and BoTorch v0.6.2 releases. The updated tutorials are also available on the website now: https://botorch.org/tutorials/custom_botorch_model_in_ax (albeit with missing plots, which should be fixed soon - it's just a website issue, should work fine if you run them locally).

Hopefully this answered your question. I am closing the issue, feel free to reopen if you have any follow up questions.

**Closed by saitcakmak** 2022-03-11 21:57 UTC
Labels: question

**Comment by farrokhsiar** [comment] 2022-03-28 20:23
Thanks a lot!
