### ISSUE TITLE
ModuleNotFoundError while importing AxClient

### ISSUE THREAD

**Issue by mstfbl** [facebook/Ax#391] opened 2020-09-30 22:30 UTC
Similar to Issue #387, we are seeing `ModuleNotFoundError`s while trying to import `AxClient` with Ax v0.1.15:

```
from ax.service.ax_client import AxClient
c:\hostedtoolcache\windows\python\3.7.9\x64\lib\site-packages\ax\__init__.py:31: in <module>
    from ax.modelbridge import Models
c:\hostedtoolcache\windows\python\3.7.9\x64\lib\site-packages\ax\modelbridge\__init__.py:10: in <module>
    from ax.modelbridge.factory import (
c:\hostedtoolcache\windows\python\3.7.9\x64\lib\site-packages\ax\modelbridge\factory.py:22: in <module>
    from ax.modelbridge.registry import (
c:\hostedtoolcache\windows\python\3.7.9\x64\lib\site-packages\ax\modelbridge\registry.py:48: in <module>
    from ax.models.torch.botorch_modular.model import BoTorchModel
E   ModuleNotFoundError: No module named 'ax.models.torch.botorch_modular'
```

This error is occurring on Windows, MacOS, and Ubuntu Linux. BoTorch v0.3.1 is already installed.

**Comment by stevemandala** [comment] 2020-09-30 22:48
Hey @mstfbl, this is related to #387, we've got a fix incoming and will push a small release soon with the fix

**Comment by stevemandala** [comment] 2020-09-30 22:49
(Closing as duplicate of #387 )

**Closed by stevemandala** 2020-09-30 22:49 UTC
