### ISSUE TITLE
Error : Try again with more data

### ISSUE THREAD

**Issue by Fa20** [facebook/Ax#2532] opened 2024-06-21 15:43 UTC
Hallo
sometimes I run the code and shows the result as in the plot below :  
![grafik](https://github.com/facebook/Ax/assets/44325972/f178a89c-9fbf-487b-94f4-c96e96bd0c22)
 some trials which are not saisfy the nonliner condition shows as Running.

The second Problem which I have it sometimes I run the code and I got  tc.block_continued_generation_error(
/python3.10/site-packages/ax/modelbridge/transition_criterion.py", line 378, in block_continued_generation_error
    raise DataRequiredError(
ax.exceptions.core.DataRequiredError: All trials for current model have been generated, but not enough data has been observed to fit next model. Try again when more data are available.

how can I avoid such this error  becuase I will do run simulation top calculate the  objective functions and I got this error  means that I need to run the simulation many times till I get one trail   and way to fix this error

**Comment by bernardbeckerman** [comment] 2024-06-21 15:53
Hi @Fa20,

In order for me to better assist you, and so this can serve as a better source for future readers, please include the exact code that created this error, formatted in Markdown code blocks ([link](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#quoting-code)) so that anyone reading can recreate the issue in their own environment. Please use proper indentation and include the full traceback that you ran into also (also in a code block). Lastly, please include the full dataframe output, ideally formatted as a Markdown table ([link](https://www.codecademy.com/resources/docs/markdown/tables)) so readers can better understand the state of your experiment at-a-glance.

**Comment by Fa20** [comment] 2024-06-21 16:09
`def p2():

   
    objective_1_result = float(input("Enter the observed result for Objective 1 (to maximize): "))
    return objective_1_result
def p_1():
    
    objective_2_result = float(input("Enter the observed result for Objective 2 (to minimize): "))
    return objective_2_result




def evaluate_parameters(params:dict)->dict:
    
    x1=params.get('x1')
    x2=params.get('x2')
   x2=params.get('x3')
    x4=params.get(x'x4)
    x5=params.get('x5)
    ### constrained 1
    
         
    s_dist =( 360 / x1) 
    s_length_ = (
            (x1 / np.tan(np.radians(x3)))
            / (x5 * math.pi)
            * 360
        )
    s_filter= (s_length / s_dist)
    
    ### constrained 2
    second_condition
    # constrained 3

    third_condition

    ### constrained 4
    fourth_condition
     
    #share_rate_constrained= 10<=share_rate<=100
    if   (second_condition) and (s_filter >=1.5)  and third_conditionn) and (fourth_condition):
        logger.info("Parameters met the filter conditions/constraints")
        data_out=pd.DataFrame([params])
        
       
        return {"objective_1": (p_2(),0.0), "objective_2": (p_1(),0.0),"s_filter":(s_filter, 0.0)
                ,"fourth_condition":(fourth_conditio,0.0),"third_condition":(third_condition,0.0),"second_condition":(second_condition, 0.0)}
   
    
    else:
        logger.info("Parameters did not meet the filter conditions/constraints")
        return None
    
    
def setup_experiment()->AxClient():
    
    try:
        ax_client = AxClient.load_from_json_file("experiment_state.json")
        logger.info("loading existing experiment.")
        print("loading existing experiment.")
    except FileNotFoundError:    
        parameters=[
            {'name':"x1", 'type':'fixed','value' :10},
            {'name':"x2", 'type':'fixed','value' :18},
                .... rest of parameters
            
        ] 
        ax_client=AxClient(enforce_sequential_optimization=True)   

        ax_client.create_experiment(name='moo_experiment',
                    parameters=parameters,
                    objectives={"objective_1":ObjectiveProperties(minimize=False),
                    
                    "objective_2":ObjectiveProperties(minimize=True)
                    },
                    
        



        )
    return ax_client

def run_experiment(ax_client:AxClient,num_trials: int=100,checkpoint_interval:int=1)->None:
   
    

    for i in range(num_trials):
        print('second print')
        parameters, trial_index=ax_client.get_next_trial()
        
        result=evaluate_parameters(parameters)
        if result is not None:
            #print('hallo')
            ax_client.complete_trial(trial_index=trial_index, raw_data=result) 
            print(f"Checkpoint after{i+1} trials")
            ax_client.save_to_json_file("experiment_state.json")
            if (i+1)% checkpoint_interval==0:
                objectives = ax_client.experiment.optimization_config.objective.objectives
                objective11 = ax_client.experiment.optimization_config.objective.metrics[0]
                objective12 = ax_client.experiment.optimization_config.objective.metrics[1]
                
                frontier = compute_posterior_pareto_frontier(
                    experiment=ax_client.experiment,
                    data=ax_client.experiment.fetch_data(),
                    primary_objective=objective12,
                    secondary_objective=objective11,
                    absolute_metrics=["objective_1", "objective_2"],
                    num_points=2,
                )
                render(plot_pareto_frontier(frontier, CI_level=0.90))
                print(f"Checkpoint after{i+1} trials")
                ax_client.save_to_json_file("experiment_state.json")     

`

**Comment by Fa20** [comment] 2024-06-21 16:13
@bernardbeckerman  the above code describe how looks like my code . I have instead 12 Prameters but I insert just two of them in the above code  in order not to make it very long code  for the reader.  The idea that if the 4 condition are true(are non linear conditions) I used this values to  make simulation and ebter the values of the objective functions an so but at the same time I'm saveing and load the experiment to avoid run the simulation all the time

**Comment by bernardbeckerman** [comment] 2024-06-21 16:59
That's better, but I'm still not sure the formatting is turning out as you expect. For instance I'm seeing the following in the GitHub UI:
<img width="861" alt="image" src="https://github.com/facebook/Ax/assets/7953022/803610ac-0bb3-4ef2-ae47-815c6c548e22">

when I'm assuming your intent is more like the following

```python
def p2():
    objective_1_result = float(input("Enter the observed result for Objective 1 (to maximize): "))
    return objective_1_result

def p_1():
    objective_2_result = float(input("Enter the observed result for Objective 2 (to minimize): "))
    return objective_2_result

def evaluate_parameters(params:dict)->dict:
    x1=params.get('x1')
    x2=params.get('x2')
    x2=params.get('x3')
    x4=params.get(x'x4)
    x5=params.get('x5)
```
etc.

There are also a couple of errors in your posted code (e.g., `params.get(x'x4)` above instead of `params.get('x4')` which I'm assuming was your intention) which leads me to believe you're not copy-pasting it from where you're running it, or that something is going wrong while doing so. Is that right? If so, is it possible to copy code over using the following procedure by using triple-backticks like in the following examples?
For python code:
````
```python
<<copy-paste your code directly from where you have run it to generate the error you're reporting>>
```
````

Otherwise, e.g., for error messages:
````
```
<<copy paste the full error message with traceback>>
```
````

Also, you can use the "Preview" tab at the top of this edit window to see how your draft will look, and make sure the formatting appears correctly. Does that help? As it stands I have to do a lot of manual editing of your posted code to make it work.

**Comment by bernardbeckerman** [comment] 2024-06-21 17:02
Also, it would be best if you would be able to create a "Minimal, Reproducible Example", since that will help me more easily reproduce the issue on my end, and will make this issue easier to follow for future readers. Please see the explanation on stackoverflow for a better idea of how to put this together ([link](https://stackoverflow.com/help/minimal-reproducible-example)).

**Comment by Fa20** [comment] 2024-06-21 17:06
```python
<<def p2():
    objective_1_result = float(input("Enter the observed result for Objective 1 (to maximize): "))
    return objective_1_result

def p_1():
    objective_2_result = float(input("Enter the observed result for Objective 2 (to minimize): "))
    return objective_2_result

def evaluate_parameters(params:dict)->dict:
    x1=params.get('x1')
    x2=params.get('x2')
    x2=params.get('x3')
    x4=params.get('x4')
    x5=params.get('x5)>>
```
yes this correct and x4 was typer error

**Comment by Fa20** [comment] 2024-06-21 17:08
sometimes the code run  but keep some experiment ruining and when I load the experiment show the problem that there are not enogh data try again with more data 
![grafik](https://github.com/facebook/Ax/assets/44325972/4258c7bb-c7fe-4dfc-a56e-9f7b3c05506e)

**Comment by Fa20** [comment] 2024-06-21 17:13
```
<<INFO - Parameters did not meet the filter conditions/constraints
second print
Traceback (most recent call last):
  File "user_path./data/optimizer.py", line 297, in <module>
    run_experiment(ax_client)
  File "user_path./data/optimizer.py", line 206, in run_experiment
    parameters, trial_index=ax_client.get_next_trial()
  File "user_path./data/lib/python3.10/site-packages/ax/utils/common/executils.py", line 163, in actual_wrapper
    return func(*args, **kwargs)
  File "user_path./datalib/python3.10/site-packages/ax/service/ax_client.py", line 539, in get_next_trial
    generator_run=self._gen_new_generator_run(
  File "user_path./data/lib/python3.10/site-packages/ax/service/ax_client.py", line 1790, in _gen_new_generator_run
    return not_none(self.generation_strategy).gen(
  File "user_path./data/lib/python3.10/site-packages/ax/modelbridge/generation_strategy.py", line 370, in gen
    return self._gen_multiple(
  File "user_path./data/lib/python3.10/site-packages/ax/modelbridge/generation_strategy.py", line 669, in _gen_multiple
    self._maybe_move_to_next_step()
  File "user_path./data/lib/python3.10/site-packages/ax/modelbridge/generation_strategy.py", line 749, in _maybe_move_to_next_step
    move_to_next_node, next_node = self._curr.should_transition_to_next_node(
  File "user_path./data/lib/python3.10/site-packages/ax/modelbridge/generation_node.py", line 426, in should_transition_to_next_node
    tc.block_continued_generation_error(
  File "user_path./data/lib/python3.10/site-packages/ax/modelbridge/transition_criterion.py", line 378, in block_continued_generation_error
    raise DataRequiredError(
ax.exceptions.core.DataRequiredError: All trials for current model have been generated, but not enough data has been observed to fit next model. Try again when more data are available>>
```

**Comment by Fa20** [comment] 2024-06-21 17:14
```
<<INFO - Parameters did not meet the filter conditions/constraints
second print
Traceback (most recent call last):
  File "user_path./data/optimizer.py", line 297, in <module>
    run_experiment(ax_client)
  File "user_path./data/optimizer.py", line 206, in run_experiment
    parameters, trial_index=ax_client.get_next_trial()
  File "user_path./data/lib/python3.10/site-packages/ax/utils/common/executils.py", line 163, in actual_wrapper
    return func(*args, **kwargs)
  File "user_path./datalib/python3.10/site-packages/ax/service/ax_client.py", line 539, in get_next_trial
    generator_run=self._gen_new_generator_run(
  File "user_path./data/lib/python3.10/site-packages/ax/service/ax_client.py", line 1790, in _gen_new_generator_run
    return not_none(self.generation_strategy).gen(
  File "user_path./data/lib/python3.10/site-packages/ax/modelbridge/generation_strategy.py", line 370, in gen
    return self._gen_multiple(
  File "user_path./data/lib/python3.10/site-packages/ax/modelbridge/generation_strategy.py", line 669, in _gen_multiple
    self._maybe_move_to_next_step()
  File "user_path./data/lib/python3.10/site-packages/ax/modelbridge/generation_strategy.py", line 749, in _maybe_move_to_next_step
    move_to_next_node, next_node = self._curr.should_transition_to_next_node(
  File "user_path./data/lib/python3.10/site-packages/ax/modelbridge/generation_node.py", line 426, in should_transition_to_next_node
    tc.block_continued_generation_error(
  File "user_path./data/lib/python3.10/site-packages/ax/modelbridge/transition_criterion.py", line 378, in block_continued_generation_error
    raise DataRequiredError(
ax.exceptions.core.DataRequiredError: All trials for current model have been generated, but not enough data has been observed to fit next model. Try again when more data are available>>
```

**Comment by Fa20** [comment] 2024-06-21 17:15
@bernardbeckerman  nay help to fix this error please

**Comment by Fa20** [comment] 2024-06-21 17:19
```python
<<def p2():

objective_1_result = float(input("Enter the observed result for Objective 1 (to maximize): "))
return objective_1_result

def p_1():

objective_2_result = float(input("Enter the observed result for Objective 2 (to minimize): "))
return objective_2_result

def evaluate_parameters(params:dict)->dict:

x1=params.get('x1')
x2=params.get('x2')

x2=params.get('x3')
x4=params.get('x4')
x5=params.get('x5')
### constrained 1

s_dist =( 360 / x1) 
s_length_ = (
        (x1 / np.tan(np.radians(x3)))
        / (x5 * math.pi)
        * 360
    )
s_filter= (s_length / s_dist)

### constrained 2
second_condition=
# constrained 3

third_condition=

### constrained 4
fourth_condition=
 
#share_rate_constrained= 10<=share_rate<=100
if   (second_condition) and (s_filter >=1.5)  and third_conditionn) and (fourth_condition):
    logger.info("Parameters met the filter conditions/constraints")
    data_out=pd.DataFrame([params])
    
   
    return {"objective_1": (p_2(),0.0), "objective_2": (p_1(),0.0),"s_filter":(s_filter, 0.0)
            ,"fourth_condition":(fourth_conditio,0.0),"third_condition":(third_condition,0.0),"second_condition":(second_condition, 0.0)}


else:
    logger.info("Parameters did not meet the filter conditions/constraints")
    return None

def setup_experiment()->AxClient():

try:
    ax_client = AxClient.load_from_json_file("experiment_state.json")
    logger.info("loading existing experiment.")
    print("loading existing experiment.")
except FileNotFoundError:    
    parameters=[
        {'name':"x1", 'type':'fixed','value' :10},
        {'name':"x2", 'type':'fixed','value' :18},
            .... rest of parameters
        
    ] 
    ax_client=AxClient(enforce_sequential_optimization=True)   

    ax_client.create_experiment(name='moo_experiment',
                parameters=parameters,
                objectives={"objective_1":ObjectiveProperties(minimize=False),
                
                "objective_2":ObjectiveProperties(minimize=True)
                },
                
    



    )
return ax_client

def run_experiment(ax_client:AxClient,num_trials: int=100,checkpoint_interval:int=1)->None:

for i in range(num_trials):
    print('second print')
    parameters, trial_index=ax_client.get_next_trial()
    
    result=evaluate_parameters(parameters)
    if result is not None:
        #print('hallo')
        ax_client.complete_trial(trial_index=trial_index, raw_data=result) 
        print(f"Checkpoint after{i+1} trials")
        ax_client.save_to_json_file("experiment_state.json")
        if (i+1)% checkpoint_interval==0:
            objectives = ax_client.experiment.optimization_config.objective.objectives
            objective11 = ax_client.experiment.optimization_config.objective.metrics[0]
            objective12 = ax_client.experiment.optimization_config.objective.metrics[1]
            
            frontier = compute_posterior_pareto_frontier(
                experiment=ax_client.experiment,
                data=ax_client.experiment.fetch_data(),
                primary_objective=objective12,
                secondary_objective=objective11,
                absolute_metrics=["objective_1", "objective_2"],
                num_points=2,
            )
            render(plot_pareto_frontier(frontier, CI_level=0.90))
            print(f"Checkpoint after{i+1} trials")
            ax_client.save_to_json_file("experiment_state.json")     

`
>>
```

**Comment by bernardbeckerman** [comment] 2024-06-21 18:36
@Fa20 thank you for your efforts thus far to reformat your code, though I believe there are still some issues. Please post code that works for you locally, and that is expected to reproduce the error for me as well. Without that, it is very difficult for me to discern what the issue is here.

I did notice that you're not issuing a `complete_trial` command for all trials, but rather just continuing in your optimization loop if `result is None`. Instead of doing that, consider doing the following:
\1. add `outcome_constraints` to your `AxClient.create_experiment` call, e.g., 

```
AxClient.create_experiment(
    ...,
    outcome_constraints=["s_filter >= 1.0"],
    ...,
)
```
(you can add outcome constraints more for your constraint_2,3,4 etc.)
\2. Have `evaluate_parameters()` return a dict containing an entry for `s_filter`, whether or not the constraint is violated or you've calculated your objectives. This will insert the data into your experiment and cause it to be marked as failed.
\3. run `ax_client.complete_trial` with that (potentially incomplete) dict, for all trials regardless of constraint violation.

I hope that helps! And for any further assistance, please be sure to provide minimal code that shows your issue, and that can be copied and run directly instead of needing manual alteration.

**Comment by Fa20** [comment] 2024-06-21 19:08
```python
<<
def p_2():

    
    
    objective_1_result = float(input("Enter the observed result for Objective 1 (to maximize): "))
    return objective_1_result
def p_1():
    objective_2_result = float(input("Enter the observed result for Objective 2 (to minimize): "))
    return objective_2_result




def evaluate_parameters(params:dict)->dict:
    """ 
    Filter the range of parameters and evaluate the objective functions. 
    Args:
        params(dict): A dictionary containing parameters values.
    Returns:
    dict: A dictionary  with objective results and constraint checks     
    """
    
    x1=params.get('x1')
    x2=params.get('x2')
    x3=params.get('x3')
    x4=params.get('x4')
    x5=params.get('x5')  
    x6=params.get('x6') 
    x7=params.get('x7')
    x8=params.get('x8')
    x9=params.get('x9')
    x10=params.get('x10')
    x11=params.get('x11')
    x12=params.get('x12')
    x13=params.get('x13')
    x14=params.get('x14')
    
    ### constrained 1
    
    s_dist =( 360 / x14) 
    s_length = (
            (x7 / np.tan(np.radians(x8)))
            / (x3 * math.pi)
            * 360
        )
    s_f= (s_length / s_dist)
    
    ### constrained 2
    lower_bound = x11* 1  
    upper_bound = x11* 3
    sl_r = (lower_bound <= x12) & (
            x12 <= upper_bound
        )
    
    # constrained 3

    lower_bound_vec = x9* 1.5 
    upper_bound_vec = x8 * 5
    g_filter = (lower_bound_vec < x9) & (
           x9 < upper_bound_vec
        )


    
     
    #share_rate_constrained= 10<=share_rate<=100
    if   (s_f >=1.5)   and sl_r and  ( g_filter):
        print("Parameters met the filter conditions/constraints")
        #data_out=pd.DataFrame([params])
        
        #factory = SimulationFactory(simulation_factory_config_path,Parameters(input_parameters))
        #factory.make_simulations(data_out)
        return {"objective_1": (p2(),0.0), "objective_2": (p1(),0.0),"s_f":(s_f, 0.0),"g_filter":(g_filter,0.0),s_r:(s_r, 0.0)}
   
    
    else:
        print("Parameters did not meet the filter conditions/constraints")
        return None
    
    
def setup_experiment()->AxClient():
    """
    Create an experiment of a search space and optimization configuration.

    Args:
    Returns:
    AxClient instance
    """
    
    #return ax_client
        
    try:
        ax_client = AxClient.load_from_json_file("experiment_state.json")
        print("loading existing experiment.")
    except FileNotFoundError:    
        parameters=[
            {'name':"x1", 'type':'fixed','value' :6},
            {'name':"x2", 'type':'fixed','value' :18},
                {'name':'x3', 'type':'fixed','value' :30},
                {'name':"x6", 'type':'range','bounds' :[10, 20],"value_type":"float"},
                
                {'name':"x7", 'type':'range','bounds' :[1, 7],"value_type":"float"},
                {'name':"x8", 'type':'range','bounds' :[0.5, 1],"value_type":"float"},
                {'name':"x9", 'type':'range','bounds' :[3, 5],"value_type":"float"},
                {'name':"x10", 'type':'range','bounds' :[0,50],"value_type":"int"},
                {'name':"x11", 'type':'range','bounds' :[3, 30],"value_type":"float"},
                {'name':"x12", 'type':'range','bounds' :[4, 30],"value_type":"float"},
                {'name':"x13", 'type':'fixed','value' :30,"value_type":"int"},
                {'name':"x14", 'type':'range','bounds' :[6, 13],"value_type":"int"},
                {'name':"x5", 'type':'fixed','value' :1.0},
                {'name':"x4", 'type':'fixed','value' :1.0}
        
                    
            
        ] 
    ax_client=AxClient(enforce_sequential_optimization=True)   

    ax_client.create_experiment(name='moo_experiment',
                    parameters=parameters,
                    objectives={"objective_1":ObjectiveProperties(minimize=False),
                    
                    "objective_2":ObjectiveProperties(minimize=True)
                    },
                    
        



        )
    return ax_client

def run_experiment(ax_client: AxClient, num_trials: int = 15, checkpoint_interval: int = 1) -> None:
    for i in range(num_trials):
      
            parameters, trial_index = ax_client.get_next_trial()
            result = evaluate_parameters(parameters)
            if result is not None:
                ax_client.complete_trial(trial_index=trial_index, raw_data=result)
                #ax_client.save_to_json_file("experiment_state.json") 
                #logger.info(f"Completed trial {i + 1}")
            else:
                print(f"Skipping trial {trial_index} due to unmet conditions")

            


def plot_pareto_front(ax_client:AxClient):

    objectives = ax_client.experiment.optimization_config.objective.objectives
    objective11 = ax_client.experiment.optimization_config.objective.metrics[0]
    objective12 = ax_client.experiment.optimization_config.objective.metrics[1]


    frontier = compute_posterior_pareto_frontier(
        experiment=ax_client.experiment,
        data=ax_client.experiment.fetch_data(),
        primary_objective=objective12,
        secondary_objective=objective11,
        absolute_metrics=["objective_1", "objective_2"],
        num_points=2,
    )
    print('frontier',frontier)
    render(plot_pareto_frontier(frontier, CI_level=0.90))

    param_dicts = frontier.param_dicts
    means = frontier.means
    sems = frontier.sems

    params_df = pd.DataFrame(param_dicts)

    means_df = pd.DataFrame(means)
    sems_df = pd.DataFrame(sems)

    sems_df.columns = [f"{col}_se" for col in sems_df.columns]# stander error for the oBjecteive function

    combined_df = pd.concat([params_df, means_df, sems_df], axis=1)

    print(ax_client.generation_strategy.trials_as_df)


if __name__ == '__main__':
    ax_client=setup_experiment()
    run_experiment(ax_client)
    plot_pareto_front(ax_client)>>'''

**Comment by Fa20** [comment] 2024-06-21 19:16
@bernardbeckerman  Thanks for your answer. The other condition I can not add them to the outcome constrained becuase can be considered as mask  True/false
2- in evaluate_parmeters  ther is if condition if is true the objective should be calaculated:
if   (s_f >=1.5)   and sl_r and  ( g_filter):
        print("Parameters met the filter conditions/constraints")
        
        return {"objective_1": (p2(),0.0), "objective_2": (p1(),0.0),"s_f":(s_f, 0.0),"g_filter":(g_filter,0.0),s_r:(s_r, 0.0)}
3- could not understand your answer about point 3

it would be very nice if you can give me any help. Thanks

**Comment by bernardbeckerman** [comment] 2024-06-21 19:25
Thanks for trying to reformat your code. The format is improving, but it is still not runnable as-is. To be clear, please provide code that you yourself have run on your machine and generates the behavior you're talking about. I'll give feedback as I'm able.

> The other condition I can not add them to the outcome constrained becuase can be considered as mask True/false

Ah, yes, better to not add binary variables as outcome constraints since they're difficult for Ax to model, so only return s_f in this case, rather than the binary variables `g_filter` and `sl_r`.

> 3- could not understand your answer about point 3

Essentially what I'm saying is that `complete_trial` can be called with partial results, e.g., only a few metrics, or even no metrics (e.g., `ax_client.complete_trial({})`) and it will cause the trial to fail, which I believe is the behavior you're trying to achieve.

**Comment by Fa20** [comment] 2024-06-21 19:31
@bernardbeckerman  ok  I will  post the exact code .

1- does this means the way I used to set the condition is correct inside evaluate_parmeters and not in the outcome_constarined
3- how can I fix this problem

**Comment by bernardbeckerman** [comment] 2024-06-21 19:53
> 1. does this means the way I used to set the condition is correct inside evaluate_parmeters and not in the outcome_constarined

It would help to add an outcome constraint for `s_filter`, e.g. `outcome_constraints=["s_filter <= 1.5"]`, but do not include an outcome constraint corresponding to any of the boolean mask variables.

> 3- how can I fix this problem

Instead of

```
else:
        logger.info("Parameters did not meet the filter conditions/constraints")
        return None
```

use the following:

```
else:
        logger.info("Parameters did not meet the filter conditions/constraints")
        return {"s_filter": (s_filter, 0.0)}
```

I believe that should work as expected.

**Comment by Fa20** [comment] 2024-06-21 20:37
@bernardbeckerman  do you mean Keep everything as is it  except this condition  can be added to outcome contained and rest of conditions should be stay in evaluate _parameters  and change else to return the  s_filter but this will not fix the problem because inside the fo  in range 
  we will have completed the trial to the parameters that satisfy the conditions as well as the parameters that just satisfy s-filter ?

**Comment by bernardbeckerman** [comment] 2024-06-21 20:44
Since you're returning an incomplete set of metrics, the trial will not reach state "COMPLETED" but rather will have state "FAILED". You're returning s_filter just so Ax can include it in its model and try to avoid it in the future (see this comment - [link](https://github.com/facebook/Ax/issues/2460#issuecomment-2115746662), and note this will only work for continuous metrics, not booleans, which is why I suggest you don't create outcome_constraints for your boolean masks).

**Comment by Fa20** [comment] 2024-06-21 20:48
@bernardbeckerman   the boolean conditions should stay in evaluate  parameters  as I did or  I understood you wrong ?

**Comment by bernardbeckerman** [comment] 2024-06-21 21:18
Using nonlinear constraints with boolean masks is a complex issue, so it may be better to close this out and make a separate issue asking about this items specifically. Regarding the original quesiton, are you able to apply the changes recommended above, so that trials that don't satisfy your nonlinear conditions appear as Failed instead of Running?

**Comment by Fa20** [comment] 2024-06-21 21:35
Not exactly:so outcome castrated  will be s_fikter>1.5


And else:
 return (s_filter)

but before else what should I write in if statmen   should I keep it as I did   because we can not use else without if statment

**Comment by Fa20** [comment] 2024-06-21 21:39
@bernardbeckerman 
So outcome costrained  s_filter>1.5

and replace else instead of None   to return s_filter
and if statement   before else should stay the same with conditions and rest of code should remains the same ?

**Comment by Fa20** [comment] 2024-06-21 22:32
![grafik](https://github.com/facebook/Ax/assets/44325972/f13c7e94-f4de-42a3-95da-f37b7c57558d)
but why even we have more than 12 trials after set the outcome_constarined the code did not move to Botorch

**Comment by Fa20** [comment] 2024-06-22 09:52
@bernardbeckerman  question regarding the boolean mask:
1-mask=((x4-1.5*x5)>=0 and(x4-5x4)>=0)  can we split it to two conditions[ (x4-1.5*x5)>=0 , second condition would be (x4-5x4)>=0 ] and add them to the papameters constrained
in case that I'm working with Service API . I checked the  tutorial and  I think that is can be doen using Developer API    but is there any way to insert it in my above code which is depend on  Service API implementation?

2- what will happen if I will keep this considtions as mask but inside the evaluate_paramters  function using if statment

  if   (second_condition) and (s_filter >=1.5)  and mask  and (fourth_condition):
       

        return {"objective_1": (p_2(),0.0), "objective_2": (p_1(),0.0),"s_filter":(s_filter, 0.0)
                ,"fourth_condition":(fourth_conditio,0.0),"third_condition":(third_condition,0.0),"second_condition":(second_condition, 0.0)}


will I be able to get set of optimal values but just will required more iteration rather than include the mask in experiment which seems not easy using  Service API?

**Comment by Fa20** [comment] 2024-06-23 04:28
@bernardbeckerman  I splitted into two condition and I added each part as outcome constrained but I got this error even there are some completed trials. could you please help
```
<<---------------------------------------------------------------------------
DataRequiredError                         Traceback (most recent call last)
Cell In[64], line 249
    247 ax_client=setup_experiment()
    248 run_experiment(ax_client)
--> 249 plot_pareto_front(ax_client)

Cell In[64], line 218, in plot_pareto_front(ax_client)
    214 objective11 = ax_client.experiment.optimization_config.objective.metrics[0]
    215 objective12 = ax_client.experiment.optimization_config.objective.metrics[1]
--> 218 frontier = compute_posterior_pareto_frontier(
    219     experiment=ax_client.experiment,
    220     data=ax_client.experiment.fetch_data(),
    221     primary_objective=objective12,
    222     secondary_objective=objective11,
    223     absolute_metrics=["objective_1", "objective_2"],
    224     num_points=1,
    225 )
    226 print('frontier',frontier)
    227 render(plot_pareto_frontier(frontier, CI_level=0.90))

File ~\anaconda3\Lib\site-packages\ax\plot\pareto_utils.py:430, in compute_posterior_pareto_frontier(experiment, primary_objective, secondary_objective, data, outcome_constraints, absolute_metrics, num_points, trial_index, chebyshev)
    416 # The weights here are just dummy weights that we pass in to construct the
    417 # modelbridge. We set the weight to -1 if `lower_is_better` is `True` and
    418 # 1 otherwise. This code would benefit from a serious revamp.
    419 oc = _build_new_optimization_config(
    420     weights=np.array(
    421         [
   (...)
    428     outcome_constraints=outcome_constraints,
    429 )
--> 430 model = Models.MOO(
    431     experiment=experiment,
    432     data=data,
    433     acqf_constructor=get_PosteriorMean,
    434     optimization_config=oc,
    435 )
    437 status_quo = experiment.status_quo
    438 if status_quo:

File ~\anaconda3\Lib\site-packages\ax\modelbridge\registry.py:380, in ModelRegistryBase.__call__(self, search_space, experiment, data, silently_filter_kwargs, **kwargs)
    367 bridge_kwargs = consolidate_kwargs(
    368     kwargs_iterable=[
    369         get_function_default_arguments(bridge_class),
   (...)
    376     ),
    377 )
    379 # Create model bridge with the consolidated kwargs.
--> 380 model_bridge = bridge_class(
    381     search_space=search_space or not_none(experiment).search_space,
    382     experiment=experiment,
    383     data=data,
    384     model=model,
    385     **bridge_kwargs,
    386 )
    388 if model_setup_info.not_saved_model_kwargs:
    389     for key in model_setup_info.not_saved_model_kwargs:

File ~\anaconda3\Lib\site-packages\ax\modelbridge\torch.py:129, in TorchModelBridge.__init__(self, experiment, search_space, data, model, transforms, transform_configs, torch_dtype, torch_device, status_quo_name, status_quo_features, optimization_config, fit_out_of_design, fit_abandoned, fit_tracking_metrics, fit_on_init, default_model_gen_options)
    124     optimization_config = not_none(
    125         optimization_config or experiment.optimization_config
    126     )
    127     self.is_moo_problem = optimization_config.is_moo_problem
--> 129 super().__init__(
    130     experiment=experiment,
    131     search_space=search_space,
    132     data=data,
    133     model=model,
    134     transforms=transforms,
    135     transform_configs=transform_configs,
    136     status_quo_name=status_quo_name,
    137     status_quo_features=status_quo_features,
    138     optimization_config=optimization_config,
    139     fit_out_of_design=fit_out_of_design,
    140     fit_abandoned=fit_abandoned,
    141     fit_tracking_metrics=fit_tracking_metrics,
    142     fit_on_init=fit_on_init,
    143 )

File ~\anaconda3\Lib\site-packages\ax\modelbridge\base.py:202, in ModelBridge.__init__(self, search_space, model, transforms, experiment, data, transform_configs, status_quo_name, status_quo_features, optimization_config, fit_out_of_design, fit_abandoned, fit_tracking_metrics, fit_on_init)
    200 self.model = model
    201 if fit_on_init:
--> 202     observations, search_space = self._transform_data(
    203         observations=observations_raw,
    204         search_space=self._model_space,
    205         transforms=self._raw_transforms,
    206         transform_configs=self._transform_configs,
    207     )
    208     self._fit_if_implemented(
    209         search_space=search_space,
    210         observations=observations,
    211         time_so_far=time.monotonic() - t_fit_start,
    212     )

File ~\anaconda3\Lib\site-packages\ax\modelbridge\base.py:289, in ModelBridge._transform_data(self, observations, search_space, transforms, transform_configs, assign_transforms)
    286     transform_configs = {}
    288 for t in transforms:
--> 289     t_instance = t(
    290         search_space=search_space,
    291         observations=observations,
    292         modelbridge=self,
    293         config=transform_configs.get(t.__name__, None),
    294     )
    295     search_space = t_instance.transform_search_space(search_space)
    296     observations = t_instance.transform_observations(observations)

File ~\anaconda3\Lib\site-packages\ax\modelbridge\transforms\standardize_y.py:45, in StandardizeY.__init__(self, search_space, observations, modelbridge, config)
     37 def __init__(
     38     self,
     39     search_space: Optional[SearchSpace] = None,
   (...)
     42     config: Optional[TConfig] = None,
     43 ) -> None:
     44     if observations is None or len(observations) == 0:
---> 45         raise DataRequiredError("`StandardizeY` transform requires non-empty data.")
     46     observation_data = [obs.data for obs in observations]
     47     Ys = get_data(observation_data=observation_data)

DataRequiredError: `StandardizeY` transform requires non-empty data.>>
```

**Comment by bernardbeckerman** [comment] 2024-06-23 21:31
> and if statement before else should stay the same with conditions and rest of code should remains the same ?

Yes your if should remain the same as before.

And as for your most recent comment:
1. These masks represent linear constraints, which parameter constraints should be used. The service API accommodates this (see [link](https://ax.dev/tutorials/gpei_hartmann_service.html#2.-Set-up-experiment)) - you can add as many as you like to the list, but keep in mind that adding many (say above 5-10 or so) may affect the performance of your optimization, so try to prioritize the most important constraints if there are many.
2. Please represent linear parameter constraints via parameter_constraints as discussed in (1), and don't use your `mask` formulation to represent this. The Service API will work for this.

**Comment by bernardbeckerman** [comment] 2024-06-23 21:33
I'm closing this issue since your iterations are now showing up as failed as expected, so the original question has been addressed. If you desire more assistance, please create another issue so that can be addressed separately.

**Closed by bernardbeckerman** 2024-06-23 21:33 UTC

**Comment by Fa20** [comment] 2024-06-23 23:22
@bernardbeckerman thanks for your Answer. my last question1-after split this conditions I set some of them in the parameters constraints (2 of them)  and some of them in the outcome constraints  because looks like x1+1.5x2 and this in case of service Api can't be handel with parameters constraints  (6 constraints  and all of them needed)
Is it OK?

**Comment by bernardbeckerman** [comment] 2024-06-25 18:50
@Fa20 please consult our documentation for best practices. If you are using Ax and are obtaining unexpected results, please post the minimal reproducible example in a new issue so that we can debug, and remember to check your post for legibility and formatting for the best response.
