### ISSUE TITLE
Implement a constraint "x1*x2=32"

### ISSUE THREAD

**Issue by aleczhanshi** [facebook/Ax#263] opened 2020-03-04 15:33 UTC
Could anyone show me how to have a constraint like "x1*x2=32" using the outcome variable or "metric"? In particular, I want to add this to https://github.com/pytorch/botorch/blob/master/tutorials/custom_botorch_model_in_ax.ipynb and need a strict equal instead of GEQ or LEQ. Thanks!

**Comment by ldworkin** [comment] 2020-03-09 13:48
Duplicate of https://github.com/facebook/Ax/issues/265

**Closed by ldworkin** 2020-03-09 13:48 UTC
