### ISSUE TITLE
`NotPSDError` in gpytorch when running high-dimensional optimization with BayesOpt

### ISSUE THREAD

**Issue by thauptmann** [facebook/Ax#666] opened 2021-08-16 10:15 UTC
Dear all,

I am using Ax for a hyperparameter search experiment on neural networks. My dataset is very small and I need an estimation of the variance of my method. Therefore I use a 5x5 cross validation (cv). I use 200 iterations for the outer cv. The first three folds of the outer cv works perfectly, but in third fold around iteration 150 I am getting an gpytorch.utils.errors.NotPSDError. The weird part is that I run the same experiment with only 20 sobol iteration instead of 50 and worked fine for 8 different datasets. 

<details>
  <summary>Stack trace</summary>
Traceback (most recent call last):
  File "/*", line 345, in <module> bayesian_optimisation(args.search_iterations, args.sobol_iterations, args.load_checkpoint, args.experiment_name,
  File "/*", line 160, in bo_moli gp_ei = Models.BOTORCH(experiment=experiment, data=experiment.fetch_data())

  File "/home/*/.virtualenvs/**/lib/python3.9/site-packages/ax/modelbridge/registry.py", line 297, in __call__
    model_bridge = bridge_class(
  File "/home/*/.virtualenvs/**/lib/python3.9/site-packages/ax/modelbridge/torch.py", line 69, in __init__
    super().__init__(
  File "/home/*/.virtualenvs/**/lib/python3.9/site-packages/ax/modelbridge/base.py", line 180, in __init__
    self._fit(
  File "/home/*/.virtualenvs/**/lib/python3.9/site-packages/ax/modelbridge/torch.py", line 101, in _fit
    super()._fit(
  File "/home/*/.virtualenvs/**/lib/python3.9/site-packages/ax/modelbridge/array.py", line 100, in _fit
    self._model_fit(
  File "/home/*/.virtualenvs/**/lib/python3.9/site-packages/ax/modelbridge/torch.py", line 137, in _model_fit
    self.model.fit(
  File "/home/*/.virtualenvs/**/lib/python3.9/site-packages/ax/models/torch/botorch.py", line 294, in fit
    self.model = self.model_constructor(  # pyre-ignore [28]
  File "/home/*/.virtualenvs/**/lib/python3.9/site-packages/ax/models/torch/botorch_defaults.py", line 181, in get_and_fit_model
    mll = fit_gpytorch_model(mll, bounds=bounds)
  File "/home/*/.virtualenvs/**/lib/python3.9/site-packages/botorch/fit.py", line 126, in fit_gpytorch_model
    mll, _ = optimizer(mll, track_iterations=False, **kwargs)
  File "/home/*/.virtualenvs/**/lib/python3.9/site-packages/botorch/optim/fit.py", line 239, in fit_gpytorch_scipy
res = minimize(
  File "/home/*/.virtualenvs/**/lib/python3.9/site-packages/scipy/optimize/_minimize.py", line 623, in minimize
    return _minimize_lbfgsb(fun, x0, args, jac, bounds,
  File "/home/*/.virtualenvs/**/lib/python3.9/site-packages/scipy/optimize/lbfgsb.py", line 360, in _minimize_lbfgsb
    f, g = func_and_grad(x)
  File "/home/*/.virtualenvs/**/lib/python3.9/site-packages/scipy/optimize/_differentiable_functions.py", line 267, in fun_and_grad
    self._update_fun()
  File "/home/*/.virtualenvs/**/lib/python3.9/site-packages/scipy/optimize/_differentiable_functions.py", line 233, in _update_fun
    self._update_fun_impl()
  File "/home/*/.virtualenvs/**/lib/python3.9/site-packages/scipy/optimize/_differentiable_functions.py", line 137, in update_fun
    self.f = fun_wrapped(self.x)
  File "/home/*/.virtualenvs/**/lib/python3.9/site-packages/scipy/optimize/_differentiable_functions.py", line 134, in fun_wrapped
    return fun(np.copy(x), *args)
  File "/home/*/.virtualenvs/**/lib/python3.9/site-packages/scipy/optimize/optimize.py", line 74, in __call__
    self._compute_if_needed(x, *args)
  File "/home/*/.virtualenvs/**/lib/python3.9/site-packages/scipy/optimize/optimize.py", line 68, in _compute_if_needed
    fg = self.fun(x, *args)
  File "/home/*/.virtualenvs/**/lib/python3.9/site-packages/botorch/optim/utils.py", line 217, in _scipy_objective_and_grad
    raise e
  File "/home/*/.virtualenvs/**/lib/python3.9/site-packages/botorch/optim/utils.py", line 214, in _scipy_objective_and_grad
    loss = -mll(*args).sum()
  File "/home/*/.virtualenvs/**/lib/python3.9/site-packages/gpytorch/module.py", line 30, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/home/*/.virtualenvs/**/lib/python3.9/site-packages/gpytorch/mlls/exact_marginal_log_likelihood.py", line 62, in forward
    res = output.log_prob(target)
  File "/home/*/.virtualenvs/**/lib/python3.9/site-packages/gpytorch/distributions/multivariate_normal.py", line 147, in log_prob
    return super().log_prob(value)
  File "/home/*/.virtualenvs/**/lib/python3.9/site-packages/torch/distributions/multivariate_normal.py", line 210, in log_prob
    M = _batch_mahalanobis(self._unbroadcasted_scale_tril, diff)
  File "/home/*/.virtualenvs/**/lib/python3.9/site-packages/gpytorch/distributions/multivariate_normal.py", line 57, in _unbroadcasted_scale_tril
    ust = delazify(self.lazy_covariance_matrix.cholesky())
File "/home/*/.virtualenvs/**/lib/python3.9/site-packages/gpytorch/lazy/lazy_tensor.py", line 959, in cholesky
    chol = self._cholesky(upper=False)
  File "/home/*/.virtualenvs/**/lib/python3.9/site-packages/gpytorch/utils/memoize.py", line 59, in g
    return _add_to_cache(self, cache_name, method(self, *args, **kwargs), *args, kwargs_pkl=kwargs_pkl)
  File "/home/*/.virtualenvs/**/lib/python3.9/site-packages/gpytorch/lazy/lazy_tensor.py", line 422, in _cholesky
    cholesky = psd_safe_cholesky(evaluated_mat, upper=upper).contiguous()
  File "/home/*/.virtualenvs/**/lib/python3.9/site-packages/gpytorch/utils/cholesky.py", line 108, in psd_safe_cholesky
    L = _psd_safe_cholesky(A, out=out, jitter=jitter, max_tries=max_tries)
  File "/home/*/.virtualenvs/**/lib/python3.9/site-packages/gpytorch/utils/cholesky.py", line 48, in _psd_safe_cholesky
    raise NotPSDError(f"Matrix not positive definite after repeatedly adding jitter up to {jitter_new:.1e}.")
gpytorch.utils.errors.NotPSDError: Matrix not positive definite after repeatedly adding jitter up to 1.0e-06.
</details>
My libraries are:

Python 3.9.5
Ax = 0.2.0

<details>
<summary>Here is the loop I use to find the best parameter. </summary>

        for i in range(search_iterations):
            print(f"Running GP+EI optimization trial {i + 1} ...")

            # Reinitialize GP+EI model at each step with updated data.
            if sampling_method == 'gp':
                gp_ei = Models.BOTORCH(experiment=experiment, data=experiment.fetch_data())
                generator_run = gp_ei.gen(1)
            else:
                generator_run = sobol.gen(1)

            experiment.new_trial(generator_run=generator_run)
            experiment.eval()
</details>

**Comment by Balandat** [comment] 2021-08-16 15:13
> The weird part is that I run the same experiment with only 20 sobol iteration instead of 50 and worked fine for 8 different datasets.

Hmm this error suggests that somehow the kernel matrix over the data points is becoming very ill-conditioned. Can you tell us a bit more about the problem, specifically what the search space looks like?

**Comment by thauptmann** [comment] 2021-08-16 15:29
It is a combination of hyperparameter and neural architecture search on multi view data. Hence, we have a very high dimensional search space. Maybe random/grid search is better suited. (That's one thing we want to experiment on.)
The return value of our evaluation function is the mean of the five AUROCS and the corresponding SEM:

```
mean = np.mean(aucs_validate)
standard_error_of_mean = scipy.stats.sem(aucs_validate)
return (mean, standard_error_of_mean)
```

And that is the search space I used:
<details>
<summary>Search space </summary>

SearchSpace(
            parameters=[
                RangeParameter(name='mini_batch', lower=batch_size_lower, upper=batch_size_upper,
                               parameter_type=ParameterType.INT),
                RangeParameter(name="h_dim1", lower=dim_lower, upper=dim_upper, parameter_type=ParameterType.INT),
                RangeParameter(name="h_dim2", lower=dim_lower, upper=dim_upper, parameter_type=ParameterType.INT),
                RangeParameter(name="h_dim3", lower=dim_lower, upper=dim_upper, parameter_type=ParameterType.INT),
                RangeParameter(name="h_dim4", lower=dim_lower, upper=dim_upper, parameter_type=ParameterType.INT),
                RangeParameter(name="h_dim5", lower=dim_lower, upper=dim_upper, parameter_type=ParameterType.INT),
                RangeParameter(name="depth_1", lower=depth_lower, upper=depth_upper, parameter_type=ParameterType.INT),
                RangeParameter(name="depth_2", lower=depth_lower, upper=depth_upper, parameter_type=ParameterType.INT),
                RangeParameter(name="depth_3", lower=depth_lower, upper=depth_upper, parameter_type=ParameterType.INT),
                RangeParameter(name="depth_4", lower=depth_lower, upper=depth_upper, parameter_type=ParameterType.INT),
                RangeParameter(name="depth_5", lower=depth_lower, upper=depth_upper, parameter_type=ParameterType.INT),
                RangeParameter(name="lr_e", lower=learning_rate_lower, upper=learning_rate_upper,
                               parameter_type=ParameterType.FLOAT, log_scale=True),
                RangeParameter(name="lr_m", lower=learning_rate_lower, upper=learning_rate_upper,
                               parameter_type=ParameterType.FLOAT, log_scale=True),
                RangeParameter(name="lr_c", lower=learning_rate_lower, upper=learning_rate_upper,
                               parameter_type=ParameterType.FLOAT, log_scale=True),
                RangeParameter(name="lr_cl", lower=learning_rate_lower, upper=learning_rate_upper,
                               parameter_type=ParameterType.FLOAT, log_scale=True),
                RangeParameter(name="lr_middle", lower=learning_rate_lower, upper=learning_rate_upper,
                               parameter_type=ParameterType.FLOAT, log_scale=True),
                RangeParameter(name="dropout_rate_e", lower=drop_rate_lower, upper=drop_rate_upper,
                               parameter_type=ParameterType.FLOAT),
                RangeParameter(name="dropout_rate_m", lower=drop_rate_lower, upper=drop_rate_upper,
                               parameter_type=ParameterType.FLOAT),
                RangeParameter(name="dropout_rate_c", lower=drop_rate_lower, upper=drop_rate_upper,
                               parameter_type=ParameterType.FLOAT),
                RangeParameter(name="dropout_rate_clf", lower=drop_rate_lower, upper=drop_rate_upper,
                               parameter_type=ParameterType.FLOAT),
                RangeParameter(name="dropout_rate_middle", lower=drop_rate_lower, upper=drop_rate_upper,
                               parameter_type=ParameterType.FLOAT),
                RangeParameter(name='weight_decay', lower=weight_decay_lower, upper=weight_decay_upper, log_scale=True,
                               parameter_type=ParameterType.FLOAT),
                RangeParameter(name='gamma', lower=gamma_lower, upper=gamma_upper, parameter_type=ParameterType.FLOAT),
                RangeParameter(name='epochs', lower=epoch_lower, upper=epoch_upper, parameter_type=ParameterType.INT),
                combination_parameter,
                RangeParameter(name='margin', lower=margin_lower, upper=margin_upper, parameter_type=ParameterType.FLOAT),
            ]
        )

</details>

**Comment by Balandat** [comment] 2021-08-16 16:36
cc @dme65, @sdaulton

**Comment by lena-kashtelyan** [comment] 2021-08-16 17:11
Marking this as a "wontfix" since there does not seem to be anything to do on our end –– the problem is just not well-suited for standard BO. The suggested workaround is to use SAASBO; let us know how it goes for you, @thauptmann!

**Comment by thauptmann** [comment] 2021-08-16 19:39
Thanks for the advice Balandat. That seems like the perfect algorithm for our use case. I will change my source code and report if it run through.

**Comment by lena-kashtelyan** [comment] 2021-08-16 19:43
Closing this issue for now as it seems sufficiently discussed, but please follow up by 1) opening a new one if you have an issue with using SAASBO or 2) letting us know here if all looks good, @thauptmann!

**Closed by lena-kashtelyan** 2021-08-16 19:43 UTC
Labels: wontfix
