### ISSUE TITLE
How to do nested/hierarchical params ?

### ISSUE THREAD

**Issue by 2W-12** [facebook/Ax#468] opened 2021-01-06 00:51 UTC
Guys, any idea how to do such hyperparams tuning ?
Based on following params I want optuna to do following trials:
Trial 1: {'GROUP_1': False, 'p1_general': 4}
Trial 2: {'GROUP_1': {'p1': 1, 'p2': 4, 'p3': 5}, 'p1_general': 7}
and so on.
Is it possible ?

```
params = [
    {
        'name': 'GROUP_1', 'type': 'choice', 'values': [True, False], 'value_type': 'bool',
        'sub_params': [
            {'name': 'p1', 'type': 'range', 'bounds': [1, 14], 'value_type': 'int'},
            {'name': 'p2', 'type': 'range', 'bounds': [1, 14], 'value_type': 'int'},
            {'name': 'p3', 'type': 'range', 'bounds': [1, 14], 'value_type': 'int'},
        ]
    },
    {
        'name': 'GROUP_2', 'type': 'choice', 'values': [True, False], 'value_type': 'bool',
        'sub_params': [
            {'name': 'p1', 'type': 'range', 'bounds': [1, 14], 'value_type': 'int'},
            {'name': 'p2', 'type': 'range', 'bounds': [1, 14], 'value_type': 'int'},
            {'name': 'p3', 'type': 'range', 'bounds': [1, 14], 'value_type': 'int'},
        ]
    },
    {
        'name': 'p1_general', 'type': 'range', 'bounds': [1, 14], 'value_type': 'int'
    },
]
```

**Comment by Balandat** [comment] 2021-01-06 07:02
We don’t have support for this currently, but @dme65 has some promising work on hierarchical search spaces that would achieve exactly what you’re trying to do, likely at a better sample efficiency than Optuna.

For now though the most straightforward thing to do without doing something custom is to just use the union of all parameters and ignore the respective irrelevant ones in the different branches.

**Comment by ldworkin** [comment] 2021-01-07 02:17
Duplicate of #140

**Closed by ldworkin** 2021-01-07 02:17 UTC
Labels: enhancement
