### ISSUE TITLE
What's the use of builtin test functions?

### ISSUE THREAD

**Issue by tramchamploo** [facebook/Ax#1048] opened 2022-08-06 07:22 UTC
The Branin, the Hartmann6 etc. Really hard to find information on them online. And the plotting of these functions are wierd and have multiple global minimas. Are they specific to some certain field?
I specify my own metrics, is it necessary for me to adapt to these functions if I want to avoid getting trapped in a local minima?

**Comment by Balandat** [comment] 2022-08-06 13:27
These are common synthetic test functions for testing algorithms and are used in development and benchmarking. No need for you to worry about them if you just want to use Ax to solve your problem.

**Comment by saitcakmak** [comment] 2022-08-06 20:42
> Really hard to find information on them online.

https://www.sfu.ca/~ssurjano/optimization.html list many of the test functions we have implemented, along with some references for each function.

> And the plotting of these functions are wierd and have multiple global minimas. Are they specific to some certain field?

These have multiple global minima by design. They're generally used to benchmark global optimization algorithms (such as BO or evolutionary algorithms) where the goal is to find the global minima / maxima.

**Comment by tramchamploo** [comment] 2022-08-08 07:09
Thanks for answering. I have some other questions. How does ax handle category values in GP? Since ax doesn't support conditional parameter space, is it a good way to just omit 'invalid' param combinations in evaluation?

**Comment by lena-kashtelyan** [comment] 2022-08-08 18:32
@tramchamploo, let me open a new issue re: category values, to make sure folks can find it if they have the same question. I'll close this one as it has been answered.

**Closed by lena-kashtelyan** 2022-08-08 18:32 UTC
Labels: question
