### ISSUE TITLE
get_contour_plot does not work if insufficient iterations / wrong error message

### ISSUE THREAD

**Issue by dqii** [facebook/Ax#181] opened 2019-10-10 19:28 UTC
This is for the service API.

I got the error
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-19-20016e2f84ef> in <module>
      2     param_x="test_min_channel_height",
      3     param_y="test_max_channel_height",
----> 4     metric_name="value"
      5 ))

~/miniconda3/lib/python3.7/site-packages/ax/service/ax_client.py in get_contour_plot(self, param_x, param_y, metric_name)
    490                     param_x=param_x,
    491                     param_y=param_y,
--> 492                     metric_name=metric_name,
    493                 )
    494 

~/miniconda3/lib/python3.7/site-packages/ax/plot/contour.py in plot_contour(model, param_x, param_y, metric_name, generator_runs_dict, relative, density, slice_values, lower_is_better, fixed_features, trial_index)
    147         generator_runs_dict=generator_runs_dict,
    148         density=density,
--> 149         slice_values=slice_values,
    150     )
    151     config = {

~/miniconda3/lib/python3.7/site-packages/ax/plot/contour.py in _get_contour_predictions(model, x_param_name, y_param_name, metric, generator_runs_dict, density, slice_values, fixed_features)
     82         fixed_features = ObservationFeatures(parameters={})
     83 
---> 84     fixed_values = get_fixed_values(model, slice_values)
     85 
     86     param_grid_obsf = []

~/miniconda3/lib/python3.7/site-packages/ax/plot/helper.py in get_fixed_values(model, slice_values, trial_index)
    442                 setx[p_name] = Counter(vals).most_common(1)[0][0]
    443             elif isinstance(parameter, RangeParameter):
--> 444                 setx[p_name] = parameter._cast(np.mean(vals))
    445 
    446     if slice_values is not None:

~/miniconda3/lib/python3.7/site-packages/ax/core/parameter.py in _cast(self, value)
    288         # pyre-fixme[29]: `Union[Type[bool], Type[float], Type[int], Type[str]]` is
    289         #  not a function.
--> 290         return self.python_type(value)
    291 
    292     def __repr__(self) -> str:

ValueError: cannot convert float NaN to integer
```
When running get_contour_plot, which was strange because when I ran ax.get_trials_data_frame().sort_values('trial_index'), none of the values were NaN.

I tried to replicate this using the same setup as in this link: https://ax.dev/tutorials/gpei_hartmann_service.html
With 3 iterations, I get the following correct / more informative error:

```
---------------------------------------------------------------------------`
ValueError                                Traceback (most recent call last)
<ipython-input-47-701c8c598cd1> in <module>
      1 render(ax.get_contour_plot(
      2     param_x="x2",
----> 3     param_y="x3"
      4 ))

~/miniconda3/lib/python3.7/site-packages/ax/service/ax_client.py in get_contour_plot(self, param_x, param_y, metric_name)
    502                 )
    503         raise ValueError(
--> 504             f'Could not obtain contour plot of "{metric_name}" for parameters '
    505             f'"{param_x}" and "{param_y}", as a model with predictive ability, '
    506             "such as a Gaussian Process, has not yet been trained in the course "

ValueError: Could not obtain contour plot of "hartmann6" for parameters "x2" and "x3", as a model with predictive ability, such as a Gaussian Process, has not yet been trained in the course of this optimization.
```

When I created this experiment, I realized it also gave me this message which suggests I needed to have a minimum number of iterations.

```
[INFO 10-10 19:14:04] ax.service.utils.dispatch: Using Bayesian Optimization generation strategy: GenerationStrategy(name='Sobol+GPEI', steps=[Sobol for 6 arms, GPEI for subsequent arms], generated 0 arm(s) so far). Iterations after 6 will take longer to generate due to model-fitting.
```

I tried replacing x1 with {"name": "x1", "type": "choice", "values": [1,2], "value_type": "int",} to see if I could reproduce. I get the following different / less informative error:

```
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-12-701c8c598cd1> in <module>
      1 render(ax.get_contour_plot(
      2     param_x="x2",
----> 3     param_y="x3"
      4 ))

~/miniconda3/lib/python3.7/site-packages/ax/service/ax_client.py in get_contour_plot(self, param_x, param_y, metric_name)
    490                     param_x=param_x,
    491                     param_y=param_y,
--> 492                     metric_name=metric_name,
    493                 )
    494 

~/miniconda3/lib/python3.7/site-packages/ax/plot/contour.py in plot_contour(model, param_x, param_y, metric_name, generator_runs_dict, relative, density, slice_values, lower_is_better, fixed_features, trial_index)
    147         generator_runs_dict=generator_runs_dict,
    148         density=density,
--> 149         slice_values=slice_values,
    150     )
    151     config = {

~/miniconda3/lib/python3.7/site-packages/ax/plot/contour.py in _get_contour_predictions(model, x_param_name, y_param_name, metric, generator_runs_dict, density, slice_values, fixed_features)
     82         fixed_features = ObservationFeatures(parameters={})
     83 
---> 84     fixed_values = get_fixed_values(model, slice_values)
     85 
     86     param_grid_obsf = []

~/miniconda3/lib/python3.7/site-packages/ax/plot/helper.py in get_fixed_values(model, slice_values, trial_index)
    440                 setx[p_name] = parameter.value
    441             elif isinstance(parameter, ChoiceParameter):
--> 442                 setx[p_name] = Counter(vals).most_common(1)[0][0]
    443             elif isinstance(parameter, RangeParameter):
    444                 setx[p_name] = parameter._cast(np.mean(vals))

IndexError: list index out of range
```

I think maybe for some reason maybe the error message is different when I use a choice parameter? It doesn't seem to be a significant bug; get_contour_plot works fine when I use the right number of iterations, both for this toy example and for my case. Just wanted to mention since the error message confused me for a bit.

**Comment by lena-kashtelyan** [comment] 2019-10-10 19:52
`get_contour_plot` uses model predictions to construct the plot; after only a few iterations, a model with predictive ability has not been used yet (chances are, your 5-6 first trials are quasi-random, only then will Bayesian optimization kick in and the model with predictive ability will be available). We should make this error message better, but overall this behavior is not wrong: contour plot should not be available until a predictive model is.

**Comment by lena-kashtelyan** [comment] 2019-11-04 18:15
@dqii, I'm having trouble reproducing your bug; could you share the full notebook? 

One thought that I have off the top of my mind is that when you added a choice parameter, you might've ended up with a Sobol generation strategy (Service API will use that when there are move discrete values in the search space than continuous parameters). If that's not the case, I'll need to see your full notebook to figure out what bug you are running into : )

**Comment by lena-kashtelyan** [comment] 2019-12-04 16:40
Closing for now since I was not able to reproduce. @dqii, please feel free to reopen if this comes up for you again and you have a repro code snippet!

**Closed by lena-kashtelyan** 2019-12-04 16:40 UTC
Labels: bug
