### ISSUE TITLE
How to save and load experiment/model from `optimize`

### ISSUE THREAD

**Issue by HanGuo97** [facebook/Ax#87] opened 2019-05-11 00:26 UTC
Hi, from the documentation, the `optimize` function returns the `(best_parameters, values, experiment, model)` tuple. I'm wondering what's the best practices for saving these values (e.g. for visualization in a different machine)? Also, is it possible to interrupt a model and later resume from the state in the `optimize` API? Thanks!

**Comment by HanGuo97** [comment] 2019-05-14 01:16
Thanks for the response!

**Comment by ksanjeevan** [comment] 2020-05-10 17:42
@lena-kashtelyan any updates on this front? Specifically, on point 2? How can one obtained the best parameters and values from just an experiment object? Thanks!

**Comment by theinlinaung2010** [comment] 2020-07-12 20:59
@lena-kashtelyan Have you got any updates on these features? I'm trying to do the same things.

**Comment by lena-kashtelyan** [comment] 2020-07-13 16:21
Hi, @ksanjeevan, @theinlinaung2010! Sorry to have missed your tags, the issue was closed so we weren't notified in time. Feel free to reopen the issue if there is a follow-up, in the future, to make sure we get back to you as soon as we can!

For #2, you can use [`get_best_parameters`](https://github.com/facebook/Ax/blob/5a0b294e443bf93ebd7170883aac265a9bf5ee6d/ax/service/utils/best_point.py#L97) utility to find the best point on the experiment. You can also use [`exp_to_df`](https://github.com/facebook/Ax/blob/639b4ed4c202d851d9e5ccb5c4cacc1bfbe281b3/ax/plot/exp_utils.py#L32) to view the trials in your experiment as a convenient dataframe. Let me know if those don't fully address your concern!

To use storage functionality for experiment and models used in optimization, I would recommend using our Service API that is well integrated with our storage layer (you can store locally to a .json file or to an SQL backend). You can check out our [API comparison](https://ax.dev/docs/api.html) code snippets and the [Service API tutorial](https://ax.dev/tutorials/gpei_hartmann_service.html) to see how to get started and how to leverage storage.

**Comment by lena-kashtelyan** [comment] 2020-07-14 20:46
Closing since it appears that my last answer resolved the questions. @ksanjeevan, @theinlinaung2010, feel free to reopen if you have follow-ups!

**Comment by nwrim** [comment] 2021-04-07 02:54
Hi @lena-kashtelyan, I was searching through the web to see if we can explicitly save the models, and this looked like the most similar issue. I was wondering if we can locally save models, such as `ax.modelbridge.factory.get_GPEI` (e.g., if we ran m = ax.modelbridge.factory.get_GPEI(experiment=experiment, data=ax.Data(data)), we want to save `m` locally so that we can load it back at later stage). We are not using the service API, which seems to make saving quite easier. This is because we do not have an evaluation function - we just make people do some task, get the results, load and feed the data to the model.

If the model cannot be saved, is there a way where we can preserve the `predict()` functionality of the model? For context, we are running human-subject experiments, and sometimes the experiment takes weeks to run to actually get the data. We want to compare the results with the prediction the model made at that point (similar to cross-validation plot in [model example](https://ax.dev/docs/models.html), but across batches rather than CVs). Do you have any suggestions?

Let me know if anything is unclear, or if you want me to open a separate issue!

**Comment by ldworkin** [comment] 2021-04-07 12:15
Hi @nwrim ! The easiest way to accomplish what you want is probably to save the _data_ that you're using to fit the model (rather than the model itself), and then you can refit it whenever you want. If you want to take advantage of Ax's storage to do so, you would use `experiment.attach_data()` followed by `save_experiment`. Then you can use `load_experiment` and `experiment.lookup_data_for_trial` or `experiment.lookup_data_for_ts` at a later point to grab that data again and refit the model. Does that sound like it would help?

**Comment by lena-kashtelyan** [comment] 2021-04-07 15:03
> We are not using the service API, which seems to make saving quite easier. This is because we do not have an evaluation function - we just make people do some task, get the results, load and feed the data to the model.

Just wanted to quickly chime in that you don't need to have an evaluation function to use the Service API –– it's actually a perfect fit for the case of "do some task, get results, feed them back to Ax model". The `AxClient.get_next_trial` (get parameters to try) then `AxClient.complete_trial` (feed data back to Ax model) pattern is made to serve this exact purpose : ) So if you wanted to leverage the Service API and its convenient storage setup, you totally could! An evaluation function is just a stub for the purpose of the tutorial to show that one can do whatever one needs with the parameter configuration in the given trial to get the data to log back to Ax : ) This has been a source of confusion to multiple folks it seems, so we'll think about how to make it clearer in the tutorial.

Even with Service API though, what would be happening under the hood is not storage of model but what @ldworkin said above –– under the hood we will re-fit the model to new data when data is available and just store information about the model settings (and a bit of its state in some cases). So it would just be a convenience wrapper around that same functionality.

**Comment by nwrim** [comment] 2021-04-07 17:13
Hi @ldworkin and @lena-kashtelyan! Thanks for the response! I really appreciate it. 

The reason behind why I wanted to store the model, rather than the experiment+data itself, was because the model seemed to generate different suggestions when `.gen()` was called when I fit the model with the exact same data. Based on this, I guessed that the model has a slightly different prediction due to some stochastic process (we are using GPEI model) even though we are fitting it with the exact same data. We kind of wanted to preserve the model because we want to release what the model predicted at the final stage. It is good to know that model saving is not supported - I will think of how I can approach this better.

For using the service API, the greatest reason why I did not use it was because I thought adding arms that the model did not suggest (guessing through `AxClient.get_next_trial`, as you mentioned) in the next batch was not possible in the service API. Is this possible through the service API? In that case, I think I should consider changing my pipeline to service API since it looks so much easier to use!

Thanks again for the response!

**Comment by Balandat** [comment] 2021-04-07 19:52
> I guessed that the model has a slightly different prediction due to some stochastic process (we are using GPEI model) even though we are fitting it with the exact same data. We kind of wanted to preserve the model because we want to release what the model predicted at the final stage. It is good to know that model saving is not supported - I will think of how I can approach this better.

Are you concerned about the model predictions being reproducible or the candidates that the model generates? In either case, it should generally be possible to make that deterministic by fixing the random seed in the proper places (so long as you pass in the same data of course). If that would be useful we could give you some pointers on how to achieve this.

**Comment by nwrim** [comment] 2021-04-07 20:19
Hi @Balandat! Yes, we are essentially concerned about reproducibility, since we likely will have to release data from all steps (predictions, candidates, etc). It will be great if you can point us to seeding the models. I used the `get_sobol` model with seed in the first generation of random arms so that it can be reproducible, but I did not see a seed option in other models like `get_GPEI`, which are the actual BayesOpt models that we wanted to use.

**Comment by lena-kashtelyan** [comment] 2021-04-12 20:41
> For using the service API, the greatest reason why I did not use it was because I thought adding arms that the model did not suggest (guessing through AxClient.get_next_trial, as you mentioned) in the next batch was not possible in the service API. Is this possible through the service API? In that case, I think I should consider changing my pipeline to service API since it looks so much easier to use!

`AxClient.attach_trial` should be what you are looking for, I think, @nwrim! See example here: https://ax.dev/tutorials/gpei_hartmann_service.html#Special-Cases.

**Comment by Balandat** [comment] 2021-04-22 16:06
So the brute force approach would be to just try to set `torch.manual_seed` before calling `get_next_trial`. This probably will work but could have some unwanted effects on other torch things going on under the hood. 

For the dev API it's possible to pass the args down to the Modelbridge's `gen` method as 
```
model_gen_kwargs: {"optimizer_kwargs": {"options": {"seed": 1234}}}
```
(lots of dicts I know). I don't think we have this exposed in the service API though at this point, it may make sense to add an optional `seed` kwargs to `get_next_trial` so that it's easy to get determinsitic behavior.

**Comment by lena-kashtelyan** [comment] 2021-04-22 16:13
The approach @Balandat suggests above is actually also possible in the Service API, but one would have to manually construct the generation strategy and pass it to `AxClient`. Here is how:

```
from ax.modelbridge.generation_strategy import GenerationStep, GenerationStrategy
from ax.modelbridge.registry import Models

gs = GenerationStrategy(
 steps=[
    GenerationStep(
        model=Models.SOBOL,
        num_trials = 5,  # Set number of trials to generate from Sobol
        min_trials_observed = 3,  # Number of Sobol trials that must be completed with data before next generation step
        model_kwargs = {"seed": 239},  # Fix seed to something
    ),
    GenerationStep(
        model=Models.BOTORCH,
        num_trials = -1,
        max_parallelism = None,   # Can set a limit on parallelism in this step if desired
        model_gen_kwargs = {"optimizer_kwargs": {"options": {"seed": 239}}},   # Fix seed to something
      ]
 )

ax_client = AxClient(..., generation_strategy=gs)

ax_client.create_expeirment(...)  # This function will no longer auto-set the generation strategy
```

**Comment by lena-kashtelyan** [comment] 2021-04-22 16:28
@nwrim, the approach @Balandat suggests above is actually also possible in the Service API, but one would have to manually construct the generation strategy and pass it to AxClient. Here is how:

from ax.modelbridge.generation_strategy import GenerationStep, GenerationStrategy
from ax.modelbridge.registry import Models

```
gs = GenerationStrategy(
 steps=[
    GenerationStep(
        model=Models.SOBOL,
        num_trials = 5,  # Set number of trials to generate from Sobol
        min_trials_observed = 3,  # Number of Sobol trials that must be completed with data before next generation step
        model_kwargs = {"seed": 239},  # Fix seed to something
    ),
    GenerationStep(
        model=Models.BOTORCH,
        num_trials = -1,
        max_parallelism = None,   # Can set a limit on parallelism in this step if desired
        model_gen_kwargs = {"optimizer_kwargs": {"options": {"seed": 239}}},   # Fix seed to something
      ]
 )

ax_client = AxClient(..., generation_strategy=gs)

ax_client.create_experiment(...)  # This function will no longer auto-set the generation strategy
```

**Comment by nwrim** [comment] 2021-04-22 16:32
This is so, so helpful! I will be trying out the suggested approaches, both in dev API and service API, and let you know if anything does not pan out. Please feel free to close the issue!

**Comment by lena-kashtelyan** [comment] 2021-04-22 16:34
Okay! Don't hesitate to reopen if you run into any issues or have follow-up questions : )

**Closed by lena-kashtelyan** 2021-04-22 16:34 UTC
Labels: enhancement, question

**Comment by mickelindahl** [comment] 2021-06-09 08:52
This is how I recreated a model from experiment data. Did not need to call experiment.attach_data(). Only used the save and load functions from from ax import save, load

m = get_GPEI(experiment, experiment.fetch_data())

Visualize:
from ax.modelbridge.factory import get_GPEI
from ax.plot.contour import plot_contour

m = get_GPEI(experiment, experiment.fetch_data())

render(plot_contour(model=m, param_x='lr', param_y='momentum', metric_name='accuracy'))

**Comment by sgbaird** [comment] 2022-11-11 08:25
@lena-kashtelyan I have a large model that takes a while to fit since it has ~2000 datapoints across 3 objectives with ~22 parameters (a few are categorical) and two parameter constraints. Do you have any suggestions for saving and reloading of the model without refitting? Something hacky or non-portable to other machines would be fine. For example, do you know if using pickle would work? If not, I'll probably give it a try soon.
